version: "3"

services:
  db:
    image: jsurf/rpi-mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - "./nc_config/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  redis:
    image: redis
    restart: always

  app:
    image: nextcloud
    restart: always
    volumes:
      - "./nc_config/nextcloud:/var/www/html"
    environment:
      #   - VIRTUAL_HOST=
      #   - LETSENCRYPT_HOST=
      #   - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

    networks:
      - icloud-net
      - default

  cron:
    image: nextcloud
    restart: always
    volumes:
      - "./nc_config/nextcloud:/var/www/html"
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 8080:80
    volumes:
      - "./nc_config/nextcloud:/var/www/html:ro"
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - icloud-net
      - default

  # music:
  #   image: deluan/navidrome:latest
  #   ports:
  #     - 4533:4533
  #   environment:
  #     # Optional: put your config options customization here. Examples:
  #     ND_SCANSCHEDULE: 1h
  #     ND_LOGLEVEL: info  
  #     ND_BASEURL: ""
  #   volumes:
  #     - ./data:/data
  #     - ./music:/music:ro

networks:
  icloud-net:
